name: Release Mac App

on: workflow_dispatch

env:
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
  VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
  VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}

jobs:
  release-macos-application:
    runs-on: macos-latest
    steps:
      - name: Check out desktop-tauri repo
        uses: actions/checkout@master
        with:
          repository: surphapp/desktop-tauri
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install project dependencies
        run: yarn install

      - name: 👷‍♂️ Building MacOS application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
